import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: 'K.Y.S',
    tagline: 'Keep Yourself Safe',
    addPassword: 'Add Password',
    websiteApp: 'Website/Application',
    category: 'Category',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Generate',
    saving: 'Saving...',
    help: 'Help',
    search: 'Search passwords...',
    noPasswords: 'No passwords found.',
    loading: 'Loading...',
    edit: 'Edit',
    delete: 'Delete',
    editEntry: 'Edit Entry',
    deleteEntry: 'Delete Entry',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    confirmDelete: 'Are you sure you want to delete',
    cannotUndo: 'This action cannot be undone.',
    site: 'Site',
    optional: 'Optional',
    games: 'Games',
    email: 'Email',
    socials: 'Socials',
    apps: 'Apps',
    bank: 'Bank',
    shopping: 'Shopping',
    work: 'Work',
    entertainment: 'Entertainment',
    uncategorized: 'Uncategorized',
    enterWebsite: 'Enter website/app',
    enterUsername: 'Enter username/email',
    enterPassword: 'Enter password',
    clearFilter: 'Clear filter',
    notes: 'Notes',
    notesPlaceholder: 'Add notes (security questions, etc.)',
    weak: 'Weak',
    fair: 'Fair',
    good: 'Good',
    strong: 'Strong',
    export: 'Export',
    import: 'Import',
    exportSuccess: 'Passwords exported successfully!',
    importSuccess: 'Passwords imported successfully!',
    duplicate: 'Duplicate',
    duplicateWarning: 'An entry for this site and username already exists.',
    addAnyway: 'Add Anyway',
    totalPasswords: 'Total Passwords',
    viewAll: 'View All',
    recentlyAdded: 'Recently Added',
    byCategory: 'By Category',
    setupTitle: "Create your master password",
    setupIntro: "This one password unlocks all your other passwords. You'll type it every time you open KYS.",
    setupExisting: "Your saved passwords will be encrypted with it.",
    masterPassword: "Master password",
    confirmPassword: "Type it again",
    passwordTooShort: "Use at least 8 characters.",
    passwordsDontMatch: "The passwords don't match.",
    createVault: "Create",
    working: "Please wait...",
    unlockTitle: "Welcome back",
    unlockIntro: "Enter your master password to open your passwords.",
    unlock: "Unlock",
    wrongPassword: "Wrong password. Try again.",
    forgotPassword: "Forgot password?",
    recoverTitle: "Use your recovery kit",
    recoverIntro: "Type the code from your recovery kit, then choose a new master password.",
    recoveryCode: "Recovery code",
    newPassword: "New master password",
    wrongRecoveryCode: "That code doesn't match. Check it and try again.",
    recoverSubmit: "Set new password",
    back: "Back",
    vaultErrorTitle: "KYS couldn't open your passwords",
    kitTitle: "Your Recovery Kit",
    kitIntro: "If you ever forget your master password, this code is the only way back in. Nobody can reset your password without it.",
    kitStore: "Print it or write it down, and keep it with your important papers or give it to someone you trust.",
    kitPrint: "Print / Save as PDF",
    kitConfirm: "To make sure you saved it, type the last 4 characters:",
    kitDone: "I've saved it, continue",
    kitCreated: "Created",
    kitHowTo: "Forgot your master password? Open KYS, click \"Forgot password?\", and type this code.",
    kitWarning: "Anyone with this code and access to your computer can open your passwords.",
    security: "Security",
    lock: "Lock",
    changePassword: "Change master password",
    currentPassword: "Current master password",
    passwordChanged: "Master password changed.",
    newKit: "Create a new recovery kit",
    newKitWarning: "Your old recovery kit will stop working. Do this if you lost it or someone else may have seen it.",
    newKitButton: "Create new kit",
    length: "Length",
    symbols: "Symbols",
    remember: "Remember on this computer",
    rememberDesc: "Open KYS without typing your master password on this computer.",
    rememberWarning: "Anyone who can sign in to your account on this computer can then open your passwords. Your master password and recovery kit keep working.",
    rememberUnavailable: "This computer can't store it securely.",
    unlockRemembered: "Unlock on this computer",
    rememberFailed: "The saved unlock on this computer no longer works. Use your master password.",
    or: "or",
    exportTitle: "Export passwords",
    exportIntro: "Creates a password-protected file you can copy to another computer (for example on a USB flash drive) and import into KYS there. Enter your master password to continue.",
    exportUseMaster: "Protect the file with my master password",
    filePassword: "File password",
    exportWarning: "Anyone who has this file and its password can read your passwords.",
    exportButton: "Export",
    exportDone: "Passwords exported:",
    importTitle: "Import passwords",
    importIntro: "Enter the password this file was exported with. Often it's the master password of the KYS it came from.",
    importButton: "Import",
    importDone: "Passwords imported:",
    importSkipped: "Skipped (already saved or incomplete):",
    notExportFile: "This isn't a KYS export file.",
    close: "Close",
    weakPasswords: "Weak",
    reusedPasswords: "Reused",
    oldPasswords: "Old (90+ days)",
    reusedBadge: "Reused",
    oldBadge: "Old",
    weakHint: "Easy to guess. Click edit, generate a new password, and change it on the website too.",
    reusedHint: "The same password is used for more than one account. If one site leaks it, the others are at risk. Give each account its own.",
    oldHint: "Not changed in over 90 days. Worth updating for important accounts like email and banking.",
    noIssues: "Nothing to fix here.",
    favoritesOnly: "Show favorites only",
    addFavorite: "Add to favorites",
    removeFavorite: "Remove from favorites",
    sortBy: "Sort",
    sortName: "Name (A–Z)",
    sortNewest: "Recently added",
    sortChanged: "Recently changed",
    whoIsUsing: "Who's using KYS?",
    addPerson: "Add person",
    newProfile: "New profile",
    welcomeTitle: "Welcome to KYS",
    welcomeIntro: "Everyone who uses this computer can have their own profile, with their own master password and passwords. Nobody can open someone else's profile without its password.",
    profileName: "Name",
    profileNamePlaceholder: "e.g. Mom",
    createProfile: "Create profile",
    switchProfile: "Switch profile",
    nameTaken: "Another profile already uses that name.",
    nameInvalid: "Enter a name (up to 30 characters).",
    profileSection: "Profile name",
    saveName: "Save",
    nameSaved: "Name saved.",
    rememberConfirmTitle: "Turn on Remember on this computer?",
    rememberConfirmText: "Anyone who uses this Windows account on this computer will be able to open this profile's passwords without the master password. If other people use this computer with the same Windows login, only turn this on if you're OK with them seeing your passwords.",
    rememberConfirmYes: "I understand, turn it on",
    deleteProfile: "Delete this profile",
    deleteProfileWarning: "Deletes this profile and all its saved passwords from this computer. This can't be undone. Export your passwords first if you want to keep them.",
    deleteProfileButton: "Delete profile",
  },
  es: {
    appName: 'K.Y.S',
    tagline: 'Mantente Seguro',
    addPassword: 'Agregar Contraseña',
    websiteApp: 'Sitio Web/Aplicación',
    category: 'Categoría',
    usernameEmail: 'Usuario/Correo',
    password: 'Contraseña',
    generate: 'Generar',
    saving: 'Guardando...',
    help: 'Ayuda',
    search: 'Buscar contraseñas...',
    noPasswords: 'No se encontraron contraseñas.',
    loading: 'Cargando...',
    edit: 'Editar',
    delete: 'Eliminar',
    editEntry: 'Editar Entrada',
    deleteEntry: 'Eliminar Entrada',
    cancel: 'Cancelar',
    saveChanges: 'Guardar Cambios',
    confirmDelete: '¿Estás seguro de eliminar',
    cannotUndo: 'Esta acción no se puede deshacer.',
    site: 'Sitio',
    optional: 'Opcional',
    games: 'Juegos',
    email: 'Correo',
    socials: 'Redes',
    apps: 'Apps',
    bank: 'Banco',
    shopping: 'Compras',
    work: 'Trabajo',
    entertainment: 'Entretenimiento',
    uncategorized: 'Sin categoría',
    enterWebsite: 'Ingresa sitio web/app',
    enterUsername: 'Ingresa usuario/correo',
    enterPassword: 'Ingresa contraseña',
    clearFilter: 'Limpiar filtro',
    notes: 'Notas',
    notesPlaceholder: 'Agregar notas (preguntas de seguridad, etc.)',
    weak: 'Débil',
    fair: 'Regular',
    good: 'Buena',
    strong: 'Fuerte',
    export: 'Exportar',
    import: 'Importar',
    exportSuccess: '¡Contraseñas exportadas!',
    importSuccess: '¡Contraseñas importadas!',
    duplicate: 'Duplicado',
    duplicateWarning: 'Ya existe una entrada para este sitio y usuario.',
    addAnyway: 'Agregar de todos modos',
    totalPasswords: 'Total de Contraseñas',
    viewAll: 'Ver Todo',
    recentlyAdded: 'Agregados Recientemente',
    byCategory: 'Por Categoría',
    setupTitle: "Crea tu contraseña maestra",
    setupIntro: "Esta contraseña desbloquea todas tus demás contraseñas. La escribirás cada vez que abras KYS.",
    setupExisting: "Tus contraseñas guardadas se cifrarán con ella.",
    masterPassword: "Contraseña maestra",
    confirmPassword: "Escríbela de nuevo",
    passwordTooShort: "Usa al menos 8 caracteres.",
    passwordsDontMatch: "Las contraseñas no coinciden.",
    createVault: "Crear",
    working: "Un momento...",
    unlockTitle: "Bienvenido de nuevo",
    unlockIntro: "Ingresa tu contraseña maestra para abrir tus contraseñas.",
    unlock: "Desbloquear",
    wrongPassword: "Contraseña incorrecta. Inténtalo de nuevo.",
    forgotPassword: "¿Olvidaste tu contraseña?",
    recoverTitle: "Usa tu kit de recuperación",
    recoverIntro: "Escribe el código de tu kit de recuperación y elige una nueva contraseña maestra.",
    recoveryCode: "Código de recuperación",
    newPassword: "Nueva contraseña maestra",
    wrongRecoveryCode: "Ese código no coincide. Revísalo e inténtalo de nuevo.",
    recoverSubmit: "Guardar nueva contraseña",
    back: "Volver",
    vaultErrorTitle: "KYS no pudo abrir tus contraseñas",
    kitTitle: "Tu Kit de Recuperación",
    kitIntro: "Si alguna vez olvidas tu contraseña maestra, este código es la única forma de volver a entrar. Nadie puede restablecer tu contraseña sin él.",
    kitStore: "Imprímelo o anótalo, y guárdalo con tus documentos importantes o dáselo a alguien de confianza.",
    kitPrint: "Imprimir / Guardar como PDF",
    kitConfirm: "Para confirmar que lo guardaste, escribe los últimos 4 caracteres:",
    kitDone: "Ya lo guardé, continuar",
    kitCreated: "Creado",
    kitHowTo: "¿Olvidaste tu contraseña maestra? Abre KYS, haz clic en \"¿Olvidaste tu contraseña?\" y escribe este código.",
    kitWarning: "Cualquiera con este código y acceso a tu computadora puede abrir tus contraseñas.",
    security: "Seguridad",
    lock: "Bloquear",
    changePassword: "Cambiar contraseña maestra",
    currentPassword: "Contraseña maestra actual",
    passwordChanged: "Contraseña maestra cambiada.",
    newKit: "Crear un nuevo kit de recuperación",
    newKitWarning: "Tu kit anterior dejará de funcionar. Hazlo si lo perdiste o si alguien más pudo verlo.",
    newKitButton: "Crear nuevo kit",
    length: "Longitud",
    symbols: "Símbolos",
    remember: "Recordar en esta computadora",
    rememberDesc: "Abre KYS sin escribir tu contraseña maestra en esta computadora.",
    rememberWarning: "Cualquiera que pueda iniciar sesión en tu cuenta de esta computadora podrá abrir tus contraseñas. Tu contraseña maestra y tu kit de recuperación siguen funcionando.",
    rememberUnavailable: "Esta computadora no puede guardarlo de forma segura.",
    unlockRemembered: "Desbloquear en esta computadora",
    rememberFailed: "El desbloqueo guardado en esta computadora ya no funciona. Usa tu contraseña maestra.",
    or: "o",
    exportTitle: "Exportar contraseñas",
    exportIntro: "Crea un archivo protegido con contraseña que puedes copiar a otra computadora (por ejemplo en una memoria USB) e importar en KYS allí. Ingresa tu contraseña maestra para continuar.",
    exportUseMaster: "Proteger el archivo con mi contraseña maestra",
    filePassword: "Contraseña del archivo",
    exportWarning: "Cualquiera que tenga este archivo y su contraseña puede leer tus contraseñas.",
    exportButton: "Exportar",
    exportDone: "Contraseñas exportadas:",
    importTitle: "Importar contraseñas",
    importIntro: "Ingresa la contraseña con la que se exportó este archivo. Suele ser la contraseña maestra del KYS de donde viene.",
    importButton: "Importar",
    importDone: "Contraseñas importadas:",
    importSkipped: "Omitidas (ya guardadas o incompletas):",
    notExportFile: "Este no es un archivo de exportación de KYS.",
    close: "Cerrar",
    weakPasswords: "Débiles",
    reusedPasswords: "Repetidas",
    oldPasswords: "Antiguas (90+ días)",
    reusedBadge: "Repetida",
    oldBadge: "Antigua",
    weakHint: "Fáciles de adivinar. Haz clic en editar, genera una contraseña nueva y cámbiala también en el sitio web.",
    reusedHint: "La misma contraseña se usa en más de una cuenta. Si un sitio la filtra, las demás quedan en riesgo. Usa una distinta para cada cuenta.",
    oldHint: "Sin cambiar en más de 90 días. Conviene actualizarlas en cuentas importantes como el correo y el banco.",
    noIssues: "Nada que arreglar aquí.",
    favoritesOnly: "Mostrar solo favoritos",
    addFavorite: "Agregar a favoritos",
    removeFavorite: "Quitar de favoritos",
    sortBy: "Ordenar",
    sortName: "Nombre (A–Z)",
    sortNewest: "Agregadas recientemente",
    sortChanged: "Cambiadas recientemente",
    whoIsUsing: "¿Quién está usando KYS?",
    addPerson: "Agregar persona",
    newProfile: "Nuevo perfil",
    welcomeTitle: "Bienvenido a KYS",
    welcomeIntro: "Cada persona que usa esta computadora puede tener su propio perfil, con su propia contraseña maestra y sus contraseñas. Nadie puede abrir el perfil de otra persona sin su contraseña.",
    profileName: "Nombre",
    profileNamePlaceholder: "p. ej. Mamá",
    createProfile: "Crear perfil",
    switchProfile: "Cambiar de perfil",
    nameTaken: "Otro perfil ya usa ese nombre.",
    nameInvalid: "Escribe un nombre (hasta 30 caracteres).",
    profileSection: "Nombre del perfil",
    saveName: "Guardar",
    nameSaved: "Nombre guardado.",
    rememberConfirmTitle: "¿Activar Recordar en esta computadora?",
    rememberConfirmText: "Cualquiera que use esta cuenta de Windows en esta computadora podrá abrir las contraseñas de este perfil sin la contraseña maestra. Si otras personas usan esta computadora con el mismo inicio de sesión de Windows, actívalo solo si no te importa que vean tus contraseñas.",
    rememberConfirmYes: "Entiendo, activarlo",
    deleteProfile: "Eliminar este perfil",
    deleteProfileWarning: "Elimina este perfil y todas sus contraseñas guardadas de esta computadora. No se puede deshacer. Exporta tus contraseñas primero si quieres conservarlas.",
    deleteProfileButton: "Eliminar perfil",
  },
  fil: {
    appName: 'K.Y.S',
    tagline: 'Panatilihing Ligtas',
    addPassword: 'Magdagdag ng Password',
    websiteApp: 'Website/Aplikasyon',
    category: 'Kategorya',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Gumawa',
    saving: 'Sine-save...',
    help: 'Tulong',
    search: 'Maghanap ng password...',
    noPasswords: 'Walang nahanap na password.',
    loading: 'Naglo-load...',
    edit: 'I-edit',
    delete: 'Tanggalin',
    editEntry: 'I-edit ang Entry',
    deleteEntry: 'Tanggalin ang Entry',
    cancel: 'Kanselahin',
    saveChanges: 'I-save ang Pagbabago',
    confirmDelete: 'Sigurado ka bang gusto mong tanggalin ang',
    cannotUndo: 'Hindi na ito maibabalik.',
    site: 'Site',
    optional: 'Opsyonal',
    games: 'Laro',
    email: 'Email',
    socials: 'Social',
    apps: 'Apps',
    bank: 'Bangko',
    shopping: 'Pamimili',
    work: 'Trabaho',
    entertainment: 'Libangan',
    uncategorized: 'Walang kategorya',
    enterWebsite: 'Ilagay ang website/app',
    enterUsername: 'Ilagay ang username/email',
    enterPassword: 'Ilagay ang password',
    clearFilter: 'I-clear ang filter',
    notes: 'Mga Nota',
    notesPlaceholder: 'Magdagdag ng mga nota (security questions, atbp.)',
    weak: 'Mahina',
    fair: 'Katamtaman',
    good: 'Mabuti',
    strong: 'Malakas',
    export: 'I-export',
    import: 'I-import',
    exportSuccess: 'Na-export na ang mga password!',
    importSuccess: 'Na-import na ang mga password!',
    duplicate: 'Duplicate',
    duplicateWarning: 'May existing na entry para sa site at username na ito.',
    addAnyway: 'Idagdag pa rin',
    totalPasswords: 'Kabuuang Password',
    viewAll: 'Tingnan Lahat',
    recentlyAdded: 'Bagong Idinagdag',
    byCategory: 'Ayon sa Kategorya',
    setupTitle: "Gumawa ng master password",
    setupIntro: "Ang password na ito ang magbubukas ng lahat ng iba mo pang password. Ita-type mo ito tuwing bubuksan mo ang KYS.",
    setupExisting: "Ie-encrypt nito ang mga naka-save mong password.",
    masterPassword: "Master password",
    confirmPassword: "I-type ulit",
    passwordTooShort: "Gumamit ng hindi bababa sa 8 character.",
    passwordsDontMatch: "Hindi magkapareho ang mga password.",
    createVault: "Gumawa",
    working: "Sandali lang...",
    unlockTitle: "Maligayang pagbabalik",
    unlockIntro: "Ilagay ang master password para mabuksan ang mga password mo.",
    unlock: "Buksan",
    wrongPassword: "Mali ang password. Subukan ulit.",
    forgotPassword: "Nakalimutan ang password?",
    recoverTitle: "Gamitin ang recovery kit",
    recoverIntro: "I-type ang code mula sa recovery kit mo, tapos pumili ng bagong master password.",
    recoveryCode: "Recovery code",
    newPassword: "Bagong master password",
    wrongRecoveryCode: "Hindi tugma ang code. Suriin at subukan ulit.",
    recoverSubmit: "I-set ang bagong password",
    back: "Bumalik",
    vaultErrorTitle: "Hindi mabuksan ng KYS ang mga password mo",
    kitTitle: "Ang Iyong Recovery Kit",
    kitIntro: "Kapag nakalimutan mo ang master password mo, ang code na ito lang ang paraan para makapasok ulit. Walang makakapag-reset ng password mo kung wala ito.",
    kitStore: "I-print o isulat ito, at itago kasama ng mahahalagang papeles mo o ibigay sa taong pinagkakatiwalaan mo.",
    kitPrint: "I-print / I-save bilang PDF",
    kitConfirm: "Para masigurong na-save mo, i-type ang huling 4 na character:",
    kitDone: "Na-save ko na, magpatuloy",
    kitCreated: "Ginawa noong",
    kitHowTo: "Nakalimutan ang master password? Buksan ang KYS, i-click ang \"Nakalimutan ang password?\", at i-type ang code na ito.",
    kitWarning: "Kahit sino na may code na ito at access sa computer mo ay mabubuksan ang mga password mo.",
    security: "Seguridad",
    lock: "I-lock",
    changePassword: "Palitan ang master password",
    currentPassword: "Kasalukuyang master password",
    passwordChanged: "Napalitan na ang master password.",
    newKit: "Gumawa ng bagong recovery kit",
    newKitWarning: "Hindi na gagana ang luma mong recovery kit. Gawin ito kung nawala mo ito o baka may ibang nakakita.",
    newKitButton: "Gumawa ng bagong kit",
    length: "Haba",
    symbols: "Simbolo",
    remember: "Tandaan sa computer na ito",
    rememberDesc: "Buksan ang KYS nang hindi tina-type ang master password sa computer na ito.",
    rememberWarning: "Kahit sino na makakapag-sign in sa account mo sa computer na ito ay mabubuksan ang mga password mo. Gagana pa rin ang master password at recovery kit mo.",
    rememberUnavailable: "Hindi ito ligtas na maiimbak ng computer na ito.",
    unlockRemembered: "Buksan sa computer na ito",
    rememberFailed: "Hindi na gumagana ang naka-save na unlock sa computer na ito. Gamitin ang master password mo.",
    or: "o",
    exportTitle: "I-export ang mga password",
    exportIntro: "Gumagawa ng file na may password na puwede mong kopyahin sa ibang computer (halimbawa sa USB flash drive) at i-import sa KYS doon. Ilagay ang master password mo para magpatuloy.",
    exportUseMaster: "Protektahan ang file gamit ang master password ko",
    filePassword: "Password ng file",
    exportWarning: "Kahit sino na may file na ito at ang password nito ay mababasa ang mga password mo.",
    exportButton: "I-export",
    exportDone: "Na-export na mga password:",
    importTitle: "I-import ang mga password",
    importIntro: "Ilagay ang password na ginamit nang i-export ang file na ito. Kadalasan ito ang master password ng KYS na pinanggalingan nito.",
    importButton: "I-import",
    importDone: "Na-import na mga password:",
    importSkipped: "Nilaktawan (naka-save na o kulang):",
    notExportFile: "Hindi ito KYS export file.",
    close: "Isara",
    weakPasswords: "Mahina",
    reusedPasswords: "Inulit",
    oldPasswords: "Luma (90+ araw)",
    reusedBadge: "Inulit",
    oldBadge: "Luma",
    weakHint: "Madaling hulaan. I-click ang edit, gumawa ng bagong password, at palitan din ito sa website.",
    reusedHint: "Iisang password ang ginagamit sa higit sa isang account. Kapag na-leak ito ng isang site, delikado rin ang iba. Bigyan ng sariling password ang bawat account.",
    oldHint: "Hindi napalitan nang mahigit 90 araw. Mainam na palitan para sa mahahalagang account gaya ng email at bangko.",
    noIssues: "Walang kailangang ayusin dito.",
    favoritesOnly: "Ipakita lang ang mga paborito",
    addFavorite: "Idagdag sa mga paborito",
    removeFavorite: "Alisin sa mga paborito",
    sortBy: "Ayusin",
    sortName: "Pangalan (A–Z)",
    sortNewest: "Bagong idinagdag",
    sortChanged: "Bagong binago",
    whoIsUsing: "Sino ang gumagamit ng KYS?",
    addPerson: "Magdagdag ng tao",
    newProfile: "Bagong profile",
    welcomeTitle: "Maligayang pagdating sa KYS",
    welcomeIntro: "Puwedeng magkaroon ng sariling profile ang bawat gumagamit ng computer na ito, na may sariling master password at mga password. Walang makakapagbukas ng profile ng iba nang wala ang password nito.",
    profileName: "Pangalan",
    profileNamePlaceholder: "hal. Nanay",
    createProfile: "Gumawa ng profile",
    switchProfile: "Palitan ang profile",
    nameTaken: "May ibang profile na gumagamit ng pangalang iyan.",
    nameInvalid: "Maglagay ng pangalan (hanggang 30 character).",
    profileSection: "Pangalan ng profile",
    saveName: "I-save",
    nameSaved: "Na-save ang pangalan.",
    rememberConfirmTitle: "I-on ang Tandaan sa computer na ito?",
    rememberConfirmText: "Kahit sino na gumagamit ng Windows account na ito sa computer na ito ay mabubuksan ang mga password ng profile na ito nang walang master password. Kung may ibang gumagamit ng computer na ito sa parehong Windows login, i-on lang ito kung okay lang sa iyo na makita nila ang mga password mo.",
    rememberConfirmYes: "Naiintindihan ko, i-on",
    deleteProfile: "Burahin ang profile na ito",
    deleteProfileWarning: "Buburahin ang profile na ito at lahat ng naka-save na password nito sa computer na ito. Hindi na ito maibabalik. I-export muna ang mga password mo kung gusto mong itago ang mga ito.",
    deleteProfileButton: "Burahin ang profile",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') || 'en';
    setLanguage(saved);
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
