import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: 'K.Y.S',
    tagline: 'Keep Yourself Safe',
    addPassword: 'Add Password',
    websiteApp: 'Website/Application',
    category: 'Category',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Generate',
    saving: 'Saving...',
    help: 'Help',
    search: 'Search passwords...',
    noPasswords: 'No passwords found.',
    loading: 'Loading...',
    edit: 'Edit',
    delete: 'Delete',
    editEntry: 'Edit Entry',
    deleteEntry: 'Delete Entry',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    confirmDelete: 'Are you sure you want to delete',
    cannotUndo: 'This action cannot be undone.',
    site: 'Site',
    optional: 'Optional',
    games: 'Games',
    email: 'Email',
    socials: 'Socials',
    apps: 'Apps',
    bank: 'Bank',
    shopping: 'Shopping',
    work: 'Work',
    entertainment: 'Entertainment',
    uncategorized: 'Uncategorized',
    enterWebsite: 'Enter website/app',
    enterUsername: 'Enter username/email',
    enterPassword: 'Enter password',
    clearFilter: 'Clear filter',
    notes: 'Notes',
    notesPlaceholder: 'Add notes (security questions, etc.)',
    weak: 'Weak',
    fair: 'Fair',
    good: 'Good',
    strong: 'Strong',
    export: 'Export',
    import: 'Import',
    exportSuccess: 'Passwords exported successfully!',
    importSuccess: 'Passwords imported successfully!',
    duplicate: 'Duplicate',
    duplicateWarning: 'An entry for this site and username already exists.',
    addAnyway: 'Add Anyway',
    totalPasswords: 'Total Passwords',
    viewAll: 'View All',
    recentlyAdded: 'Recently Added',
    byCategory: 'By Category',
  },
  es: {
    appName: 'K.Y.S',
    tagline: 'Mantente Seguro',
    addPassword: 'Agregar Contraseña',
    websiteApp: 'Sitio Web/Aplicación',
    category: 'Categoría',
    usernameEmail: 'Usuario/Correo',
    password: 'Contraseña',
    generate: 'Generar',
    saving: 'Guardando...',
    help: 'Ayuda',
    search: 'Buscar contraseñas...',
    noPasswords: 'No se encontraron contraseñas.',
    loading: 'Cargando...',
    edit: 'Editar',
    delete: 'Eliminar',
    editEntry: 'Editar Entrada',
    deleteEntry: 'Eliminar Entrada',
    cancel: 'Cancelar',
    saveChanges: 'Guardar Cambios',
    confirmDelete: '¿Estás seguro de eliminar',
    cannotUndo: 'Esta acción no se puede deshacer.',
    site: 'Sitio',
    optional: 'Opcional',
    games: 'Juegos',
    email: 'Correo',
    socials: 'Redes',
    apps: 'Apps',
    bank: 'Banco',
    shopping: 'Compras',
    work: 'Trabajo',
    entertainment: 'Entretenimiento',
    uncategorized: 'Sin categoría',
    enterWebsite: 'Ingresa sitio web/app',
    enterUsername: 'Ingresa usuario/correo',
    enterPassword: 'Ingresa contraseña',
    clearFilter: 'Limpiar filtro',
    notes: 'Notas',
    notesPlaceholder: 'Agregar notas (preguntas de seguridad, etc.)',
    weak: 'Débil',
    fair: 'Regular',
    good: 'Buena',
    strong: 'Fuerte',
    export: 'Exportar',
    import: 'Importar',
    exportSuccess: '¡Contraseñas exportadas!',
    importSuccess: '¡Contraseñas importadas!',
    duplicate: 'Duplicado',
    duplicateWarning: 'Ya existe una entrada para este sitio y usuario.',
    addAnyway: 'Agregar de todos modos',
    totalPasswords: 'Total de Contraseñas',
    viewAll: 'Ver Todo',
    recentlyAdded: 'Agregados Recientemente',
    byCategory: 'Por Categoría',
  },
  fil: {
    appName: 'K.Y.S',
    tagline: 'Panatilihing Ligtas',
    addPassword: 'Magdagdag ng Password',
    websiteApp: 'Website/Aplikasyon',
    category: 'Kategorya',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Gumawa',
    saving: 'Sine-save...',
    help: 'Tulong',
    search: 'Maghanap ng password...',
    noPasswords: 'Walang nahanap na password.',
    loading: 'Naglo-load...',
    edit: 'I-edit',
    delete: 'Tanggalin',
    editEntry: 'I-edit ang Entry',
    deleteEntry: 'Tanggalin ang Entry',
    cancel: 'Kanselahin',
    saveChanges: 'I-save ang Pagbabago',
    confirmDelete: 'Sigurado ka bang gusto mong tanggalin ang',
    cannotUndo: 'Hindi na ito maibabalik.',
    site: 'Site',
    optional: 'Opsyonal',
    games: 'Laro',
    email: 'Email',
    socials: 'Social',
    apps: 'Apps',
    bank: 'Bangko',
    shopping: 'Pamimili',
    work: 'Trabaho',
    entertainment: 'Libangan',
    uncategorized: 'Walang kategorya',
    enterWebsite: 'Ilagay ang website/app',
    enterUsername: 'Ilagay ang username/email',
    enterPassword: 'Ilagay ang password',
    clearFilter: 'I-clear ang filter',
    notes: 'Mga Nota',
    notesPlaceholder: 'Magdagdag ng mga nota (security questions, atbp.)',
    weak: 'Mahina',
    fair: 'Katamtaman',
    good: 'Mabuti',
    strong: 'Malakas',
    export: 'I-export',
    import: 'I-import',
    exportSuccess: 'Na-export na ang mga password!',
    importSuccess: 'Na-import na ang mga password!',
    duplicate: 'Duplicate',
    duplicateWarning: 'May existing na entry para sa site at username na ito.',
    addAnyway: 'Idagdag pa rin',
    totalPasswords: 'Kabuuang Password',
    viewAll: 'Tingnan Lahat',
    recentlyAdded: 'Bagong Idinagdag',
    byCategory: 'Ayon sa Kategorya',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') || 'en';
    setLanguage(saved);
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
