import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: 'K.Y.S',
    tagline: 'Keep Yourself Safe',
    addPassword: 'Add Password',
    websiteApp: 'Website/Application',
    category: 'Category',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Generate',
    saving: 'Saving...',
    help: 'Help',
    search: 'Search passwords...',
    noPasswords: 'No passwords found.',
    loading: 'Loading...',
    edit: 'Edit',
    delete: 'Delete',
    editEntry: 'Edit Entry',
    deleteEntry: 'Delete Entry',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    confirmDelete: 'Are you sure you want to delete',
    cannotUndo: 'This action cannot be undone.',
    site: 'Site',
    optional: 'Optional',
    games: 'Games',
    email: 'Email',
    socials: 'Socials',
    apps: 'Apps',
    bank: 'Bank',
    shopping: 'Shopping',
    work: 'Work',
    entertainment: 'Entertainment',
    uncategorized: 'Uncategorized',
    enterWebsite: 'Enter website/app',
    enterUsername: 'Enter username/email',
    enterPassword: 'Enter password',
    clearFilter: 'Clear filter',
    notes: 'Notes',
    notesPlaceholder: 'Add notes (security questions, etc.)',
    weak: 'Weak',
    fair: 'Fair',
    good: 'Good',
    strong: 'Strong',
    export: 'Export',
    import: 'Import',
    exportSuccess: 'Passwords exported successfully!',
    importSuccess: 'Passwords imported successfully!',
    duplicate: 'Duplicate',
    duplicateWarning: 'An entry for this site and username already exists.',
    addAnyway: 'Add Anyway',
    totalPasswords: 'Total Passwords',
    viewAll: 'View All',
    recentlyAdded: 'Recently Added',
    byCategory: 'By Category',
    setupTitle: "Create your master password",
    setupIntro: "This one password unlocks all your other passwords. You'll type it every time you open KYS.",
    setupExisting: "Your saved passwords will be encrypted with it.",
    masterPassword: "Master password",
    confirmPassword: "Type it again",
    passwordTooShort: "Use at least 8 characters.",
    passwordsDontMatch: "The passwords don't match.",
    createVault: "Create",
    working: "Please wait...",
    unlockTitle: "Welcome back",
    unlockIntro: "Enter your master password to open your passwords.",
    unlock: "Unlock",
    wrongPassword: "Wrong password. Try again.",
    forgotPassword: "Forgot password?",
    recoverTitle: "Use your recovery kit",
    recoverIntro: "Type the code from your recovery kit, then choose a new master password.",
    recoveryCode: "Recovery code",
    newPassword: "New master password",
    wrongRecoveryCode: "That code doesn't match. Check it and try again.",
    recoverSubmit: "Set new password",
    back: "Back",
    vaultErrorTitle: "KYS couldn't open your passwords",
    kitTitle: "Your Recovery Kit",
    kitIntro: "If you ever forget your master password, this code is the only way back in. Nobody can reset your password without it.",
    kitStore: "Print it or write it down, and keep it with your important papers or give it to someone you trust.",
    kitPrint: "Print / Save as PDF",
    kitConfirm: "To make sure you saved it, type the last 4 characters:",
    kitDone: "I've saved it, continue",
    kitCreated: "Created",
    kitHowTo: "Forgot your master password? Open KYS, click \"Forgot password?\", and type this code.",
    kitWarning: "Anyone with this code and access to your computer can open your passwords.",
    security: "Security",
    lock: "Lock",
    changePassword: "Change master password",
    currentPassword: "Current master password",
    passwordChanged: "Master password changed.",
    newKit: "Create a new recovery kit",
    newKitWarning: "Your old recovery kit will stop working. Do this if you lost it or someone else may have seen it.",
    newKitButton: "Create new kit",
    length: "Length",
    symbols: "Symbols",
    remember: "Remember on this computer",
    rememberDesc: "Open KYS without typing your master password on this computer.",
    rememberWarning: "Anyone who can sign in to your account on this computer can then open your passwords. Your master password and recovery kit keep working.",
    rememberUnavailable: "This computer can't store it securely.",
    unlockRemembered: "Unlock on this computer",
    rememberFailed: "The saved unlock on this computer no longer works. Use your master password.",
    or: "or",
  },
  es: {
    appName: 'K.Y.S',
    tagline: 'Mantente Seguro',
    addPassword: 'Agregar Contraseña',
    websiteApp: 'Sitio Web/Aplicación',
    category: 'Categoría',
    usernameEmail: 'Usuario/Correo',
    password: 'Contraseña',
    generate: 'Generar',
    saving: 'Guardando...',
    help: 'Ayuda',
    search: 'Buscar contraseñas...',
    noPasswords: 'No se encontraron contraseñas.',
    loading: 'Cargando...',
    edit: 'Editar',
    delete: 'Eliminar',
    editEntry: 'Editar Entrada',
    deleteEntry: 'Eliminar Entrada',
    cancel: 'Cancelar',
    saveChanges: 'Guardar Cambios',
    confirmDelete: '¿Estás seguro de eliminar',
    cannotUndo: 'Esta acción no se puede deshacer.',
    site: 'Sitio',
    optional: 'Opcional',
    games: 'Juegos',
    email: 'Correo',
    socials: 'Redes',
    apps: 'Apps',
    bank: 'Banco',
    shopping: 'Compras',
    work: 'Trabajo',
    entertainment: 'Entretenimiento',
    uncategorized: 'Sin categoría',
    enterWebsite: 'Ingresa sitio web/app',
    enterUsername: 'Ingresa usuario/correo',
    enterPassword: 'Ingresa contraseña',
    clearFilter: 'Limpiar filtro',
    notes: 'Notas',
    notesPlaceholder: 'Agregar notas (preguntas de seguridad, etc.)',
    weak: 'Débil',
    fair: 'Regular',
    good: 'Buena',
    strong: 'Fuerte',
    export: 'Exportar',
    import: 'Importar',
    exportSuccess: '¡Contraseñas exportadas!',
    importSuccess: '¡Contraseñas importadas!',
    duplicate: 'Duplicado',
    duplicateWarning: 'Ya existe una entrada para este sitio y usuario.',
    addAnyway: 'Agregar de todos modos',
    totalPasswords: 'Total de Contraseñas',
    viewAll: 'Ver Todo',
    recentlyAdded: 'Agregados Recientemente',
    byCategory: 'Por Categoría',
    setupTitle: "Crea tu contraseña maestra",
    setupIntro: "Esta contraseña desbloquea todas tus demás contraseñas. La escribirás cada vez que abras KYS.",
    setupExisting: "Tus contraseñas guardadas se cifrarán con ella.",
    masterPassword: "Contraseña maestra",
    confirmPassword: "Escríbela de nuevo",
    passwordTooShort: "Usa al menos 8 caracteres.",
    passwordsDontMatch: "Las contraseñas no coinciden.",
    createVault: "Crear",
    working: "Un momento...",
    unlockTitle: "Bienvenido de nuevo",
    unlockIntro: "Ingresa tu contraseña maestra para abrir tus contraseñas.",
    unlock: "Desbloquear",
    wrongPassword: "Contraseña incorrecta. Inténtalo de nuevo.",
    forgotPassword: "¿Olvidaste tu contraseña?",
    recoverTitle: "Usa tu kit de recuperación",
    recoverIntro: "Escribe el código de tu kit de recuperación y elige una nueva contraseña maestra.",
    recoveryCode: "Código de recuperación",
    newPassword: "Nueva contraseña maestra",
    wrongRecoveryCode: "Ese código no coincide. Revísalo e inténtalo de nuevo.",
    recoverSubmit: "Guardar nueva contraseña",
    back: "Volver",
    vaultErrorTitle: "KYS no pudo abrir tus contraseñas",
    kitTitle: "Tu Kit de Recuperación",
    kitIntro: "Si alguna vez olvidas tu contraseña maestra, este código es la única forma de volver a entrar. Nadie puede restablecer tu contraseña sin él.",
    kitStore: "Imprímelo o anótalo, y guárdalo con tus documentos importantes o dáselo a alguien de confianza.",
    kitPrint: "Imprimir / Guardar como PDF",
    kitConfirm: "Para confirmar que lo guardaste, escribe los últimos 4 caracteres:",
    kitDone: "Ya lo guardé, continuar",
    kitCreated: "Creado",
    kitHowTo: "¿Olvidaste tu contraseña maestra? Abre KYS, haz clic en \"¿Olvidaste tu contraseña?\" y escribe este código.",
    kitWarning: "Cualquiera con este código y acceso a tu computadora puede abrir tus contraseñas.",
    security: "Seguridad",
    lock: "Bloquear",
    changePassword: "Cambiar contraseña maestra",
    currentPassword: "Contraseña maestra actual",
    passwordChanged: "Contraseña maestra cambiada.",
    newKit: "Crear un nuevo kit de recuperación",
    newKitWarning: "Tu kit anterior dejará de funcionar. Hazlo si lo perdiste o si alguien más pudo verlo.",
    newKitButton: "Crear nuevo kit",
    length: "Longitud",
    symbols: "Símbolos",
    remember: "Recordar en esta computadora",
    rememberDesc: "Abre KYS sin escribir tu contraseña maestra en esta computadora.",
    rememberWarning: "Cualquiera que pueda iniciar sesión en tu cuenta de esta computadora podrá abrir tus contraseñas. Tu contraseña maestra y tu kit de recuperación siguen funcionando.",
    rememberUnavailable: "Esta computadora no puede guardarlo de forma segura.",
    unlockRemembered: "Desbloquear en esta computadora",
    rememberFailed: "El desbloqueo guardado en esta computadora ya no funciona. Usa tu contraseña maestra.",
    or: "o",
  },
  fil: {
    appName: 'K.Y.S',
    tagline: 'Panatilihing Ligtas',
    addPassword: 'Magdagdag ng Password',
    websiteApp: 'Website/Aplikasyon',
    category: 'Kategorya',
    usernameEmail: 'Username/Email',
    password: 'Password',
    generate: 'Gumawa',
    saving: 'Sine-save...',
    help: 'Tulong',
    search: 'Maghanap ng password...',
    noPasswords: 'Walang nahanap na password.',
    loading: 'Naglo-load...',
    edit: 'I-edit',
    delete: 'Tanggalin',
    editEntry: 'I-edit ang Entry',
    deleteEntry: 'Tanggalin ang Entry',
    cancel: 'Kanselahin',
    saveChanges: 'I-save ang Pagbabago',
    confirmDelete: 'Sigurado ka bang gusto mong tanggalin ang',
    cannotUndo: 'Hindi na ito maibabalik.',
    site: 'Site',
    optional: 'Opsyonal',
    games: 'Laro',
    email: 'Email',
    socials: 'Social',
    apps: 'Apps',
    bank: 'Bangko',
    shopping: 'Pamimili',
    work: 'Trabaho',
    entertainment: 'Libangan',
    uncategorized: 'Walang kategorya',
    enterWebsite: 'Ilagay ang website/app',
    enterUsername: 'Ilagay ang username/email',
    enterPassword: 'Ilagay ang password',
    clearFilter: 'I-clear ang filter',
    notes: 'Mga Nota',
    notesPlaceholder: 'Magdagdag ng mga nota (security questions, atbp.)',
    weak: 'Mahina',
    fair: 'Katamtaman',
    good: 'Mabuti',
    strong: 'Malakas',
    export: 'I-export',
    import: 'I-import',
    exportSuccess: 'Na-export na ang mga password!',
    importSuccess: 'Na-import na ang mga password!',
    duplicate: 'Duplicate',
    duplicateWarning: 'May existing na entry para sa site at username na ito.',
    addAnyway: 'Idagdag pa rin',
    totalPasswords: 'Kabuuang Password',
    viewAll: 'Tingnan Lahat',
    recentlyAdded: 'Bagong Idinagdag',
    byCategory: 'Ayon sa Kategorya',
    setupTitle: "Gumawa ng master password",
    setupIntro: "Ang password na ito ang magbubukas ng lahat ng iba mo pang password. Ita-type mo ito tuwing bubuksan mo ang KYS.",
    setupExisting: "Ie-encrypt nito ang mga naka-save mong password.",
    masterPassword: "Master password",
    confirmPassword: "I-type ulit",
    passwordTooShort: "Gumamit ng hindi bababa sa 8 character.",
    passwordsDontMatch: "Hindi magkapareho ang mga password.",
    createVault: "Gumawa",
    working: "Sandali lang...",
    unlockTitle: "Maligayang pagbabalik",
    unlockIntro: "Ilagay ang master password para mabuksan ang mga password mo.",
    unlock: "Buksan",
    wrongPassword: "Mali ang password. Subukan ulit.",
    forgotPassword: "Nakalimutan ang password?",
    recoverTitle: "Gamitin ang recovery kit",
    recoverIntro: "I-type ang code mula sa recovery kit mo, tapos pumili ng bagong master password.",
    recoveryCode: "Recovery code",
    newPassword: "Bagong master password",
    wrongRecoveryCode: "Hindi tugma ang code. Suriin at subukan ulit.",
    recoverSubmit: "I-set ang bagong password",
    back: "Bumalik",
    vaultErrorTitle: "Hindi mabuksan ng KYS ang mga password mo",
    kitTitle: "Ang Iyong Recovery Kit",
    kitIntro: "Kapag nakalimutan mo ang master password mo, ang code na ito lang ang paraan para makapasok ulit. Walang makakapag-reset ng password mo kung wala ito.",
    kitStore: "I-print o isulat ito, at itago kasama ng mahahalagang papeles mo o ibigay sa taong pinagkakatiwalaan mo.",
    kitPrint: "I-print / I-save bilang PDF",
    kitConfirm: "Para masigurong na-save mo, i-type ang huling 4 na character:",
    kitDone: "Na-save ko na, magpatuloy",
    kitCreated: "Ginawa noong",
    kitHowTo: "Nakalimutan ang master password? Buksan ang KYS, i-click ang \"Nakalimutan ang password?\", at i-type ang code na ito.",
    kitWarning: "Kahit sino na may code na ito at access sa computer mo ay mabubuksan ang mga password mo.",
    security: "Seguridad",
    lock: "I-lock",
    changePassword: "Palitan ang master password",
    currentPassword: "Kasalukuyang master password",
    passwordChanged: "Napalitan na ang master password.",
    newKit: "Gumawa ng bagong recovery kit",
    newKitWarning: "Hindi na gagana ang luma mong recovery kit. Gawin ito kung nawala mo ito o baka may ibang nakakita.",
    newKitButton: "Gumawa ng bagong kit",
    length: "Haba",
    symbols: "Simbolo",
    remember: "Tandaan sa computer na ito",
    rememberDesc: "Buksan ang KYS nang hindi tina-type ang master password sa computer na ito.",
    rememberWarning: "Kahit sino na makakapag-sign in sa account mo sa computer na ito ay mabubuksan ang mga password mo. Gagana pa rin ang master password at recovery kit mo.",
    rememberUnavailable: "Hindi ito ligtas na maiimbak ng computer na ito.",
    unlockRemembered: "Buksan sa computer na ito",
    rememberFailed: "Hindi na gumagana ang naka-save na unlock sa computer na ito. Gamitin ang master password mo.",
    or: "o",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') || 'en';
    setLanguage(saved);
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => translations[language]?.[key] || translations.en[key] || key;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
